# Explicitly use the Node.js provider
providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "git"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "bun install --frozen-lockfile",
]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
